; Aether Technology File
; Generated: Tue Aug 19 09:21:37 2025

; Aether Technology Manager Version: 1.03

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; CONTROLS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
controls(
 viewTypeUnits(
 ( maskLayout           micron     1000 )
 ( schematic            inch       160 )
 ( schematicSymbol      inch       160 )
 ( netlist              inch       160 )
 ( hierDesign           micron     1000 )
 ) ;viewTypeUnits

 mfgGridResolution(
       ( 0.001 )
 ) ;mfgGridResolution


) ;controls

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; LAYER DEFINITION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
layerDefinitions(
 techPurposes(
 ; ( PURPOSENAME          PURPOSENUM          ABBREVIATION          [ATTRIBUTES] )
 ; ( ===========          ==========          ============          ============ )
 ( dm                   2          dm         )
 ( dmblk                3          dmblk      )
 ( res                  4          res        )
 ( opcblk               5          opcblk     )
 ( text                 6          text       )
 ( bar                  7          bar        )
 ( SLOT                 8          SLOT       )
 ( slotblk              9          slotblk    )
 ( mom                  10         mom        )
 ( retblk               11         retblk     )
 ( mark                 12         mark       )
 ( p1                   256        p1         )
 ( p2                   257        p2         )
 ( mk1                  258        mk1        )
 ) ;techPurposes

 techLayers(
 ; ( LAYERNAME          LAYERNUM          ABBREVIATION         [ATTRIBUTES] )
 ; ( =========          ========          ============         ============ )
 ( ZERO                 0          ZERO       )
 ( ACT                  2          ACT        )
 ( DNW                  7          DNW        )
 ( NW1                  9          NW1        )
 ( NVT1                 17         NVT1       )
 ( PVT1                 18         PVT1       )
 ( NVT3                 21         NVT3       )
 ( PVT3                 22         PVT3       )
 ( DGOX                 27         DGOX       )
 ( TGOX                 28         TGOX       )
 ( POLY                 41         POLY       )
 ( NPD                  43         NPD        )
 ( NP                   52         NP         )
 ( PP                   53         PP         )
 ( HRP                  54         HRP        )
 ( ESD                  55         ESD        )
 ( SAB                  71         SAB        )
 ( CT                   72         CT         )
 ( MET1                 81         MET1       )
 ( MET2                 82         MET2       )
 ( MET3                 83         MET3       )
 ( MET4                 84         MET4       )
 ( MET5                 85         MET5       )
 ( MET6                 86         MET6       )
 ( MET7                 87         MET7       )
 ( MET8                 88         MET8       )
 ( VIA1                 91         VIA1       )
 ( VIA2                 92         VIA2       )
 ( VIA3                 93         VIA3       )
 ( VIA4                 94         VIA4       )
 ( VIA5                 95         VIA5       )
 ( VIA6                 96         VIA6       )
 ( VIA7                 97         VIA7       )
 ( T2M1                 100        T2M1       )
 ( T2M2                 101        T2M2       )
 ( T4M1                 102        T4M1       )
 ( T4M2                 103        T4M2       )
 ( T8M1                 104        T8M1       )
 ( T8M2                 105        T8M2       )
 ( T2V1                 110        T2V1       )
 ( T2V2                 111        T2V2       )
 ( T4V1                 112        T4V1       )
 ( T4V2                 113        T4V2       )
 ( T8V1                 114        T8V1       )
 ( T8V2                 115        T8V2       )
 ( RV                   120        RV         )
 ( CB                   121        CB         )
 ( ALPAD                122        ALPAD      )
 ( RDL                  123        RDL        )
 ( COVER                124        COVER      )
 ( BMIM                 140        BMIM       )
 ( TMIM                 141        TMIM       )
 ( IO                   150        IO         )
 ( CORE                 151        CORE       )
 ( ULLD                 152        ULLD       )
 ( UD                   153        UD         )
 ( OD                   154        OD         )
 ( SRAMALL              171        SRAMALL    )
 ( SRAMPG               172        SRAMPG     )
 ( SRAM6THD             173        SRAM6THD   )
 ( SRAM6THS             174        SRAM6THS   )
 ( SRAM8THD             176        SRAM8THD   )
 ( SRAM8THS             177        SRAM8THS   )
 ( DIODE                181        DIODE      )
 ( VARA                 182        VARA       )
 ( VARAM                183        VARAM      )
 ( VARAJ                184        VARAJ      )
 ( BJT                  185        BJT        )
 ( LDMOS                186        LDMOS      )
 ( ESDIOT               187        ESDIOT     )
 ( ESDIOE               188        ESDIOE     )
 ( RFALL                189        RFALL      )
 ( RFD                  190        RFD        )
 ( RFTER                191        RFTER      )
 ( Unrouted             200        Unroute    )
 ( Row                  201        Row        )
 ( Group                202        Group      )
 ( Cannotoccupy         203        noOcupy    )
 ( Canplace             204        Canplac    )
 ( hardFence            205        hardFnc    )
 ( softFence            206        softFnc    )
 ( y0                   207        y0         )
 ( y1                   208        y1         )
 ( y2                   209        y2         )
 ( y3                   210        y3         )
 ( y4                   211        y4         )
 ( y5                   212        y5         )
 ( y6                   213        y6         )
 ( y7                   214        y7         )
 ( y8                   215        y8         )
 ( y9                   216        y9         )
 ( designFlow           217        dsnFlow    )
 ( stretch              218        stretch    )
 ( edgeLayer            219        edgeLyr    )
 ( changedLayer         220        chngLyr    )
 ( unset                221        unset      )
 ( unknown              222        unknown    )
 ( spike                223        spike      )
 ( hiz                  224        hiz        )
 ( resist               225        resist     )
 ( drive                226        drive      )
 ( supply               227        supply     )
 ( wire                 228        wire       )
 ( pin                  229        pin        )
 ( text                 230        text       )
 ( device               231        device     )
 ( border               232        border     )
 ( snap                 233        snap       )
 ( align                234        align      )
 ( prBoundary           235        prBndry    )
 ( instance             236        instnce    )
 ( annotate             237        anotate    )
 ( marker               238        marker     )
 ( select               239        select     )
 ( grid                 251        grid       )
 ( axis                 252        axis       )
 ( hilite               253        hilite     )
 ( background           254        bkground   )
 ( PSUB                 261        PSUB       )
 ( CAP                  271        CAP        )
 ( MOMCAP               281        MOMCAP     )
 ( MOMTER               282        MOMTER     )
 ( FUTR                 291        FUTR       )
 ( FUSEALL              292        FUSEALL    )
 ( EFUSEALL             293        EFUSEALL   )
 ( POEFUSEBLK           294        POEFUSEBLK )
 ( INDDMY               301        INDDMY     )
 ( INDALL               302        INDALL     )
 ( INDVIA               303        INDVIA     )
 ( NOLVS                311        NOLVS      )
 ( MOSMF                312        MOSMF      )
 ( SUBCKTLVS            313        SUBCKTLVS  )
 ( RESCKTLVS            314        RESCKTLVS  )
 ( MOSCKTLVS            315        MOSCKTLVS  )
 ( LATCHUP              316        LATCHUP    )
 ( RFSDLVS              317        RFSDLVS    )
 ( RF5TERLVS            318        RF5TERLVS  )
 ( RF6TERLVS            319        RF6TERLVS  )
 ( VARAJMRK             320        VARAJMRK   )
 ( LDMOSSTI             321        LDMOSSTI   )
 ( FUSEDRC              322        FUSEDRC    )
 ( MOMLVS1              323        MOMLVS1    )
 ( MOMLVS2              324        MOMLVS2    )
 ( MOMLVS3              325        MOMLVS3    )
 ( MOMLVS4              326        MOMLVS4    )
 ( MOMLVS5              327        MOMLVS5    )
 ( MOMLVS6              328        MOMLVS6    )
 ( RES3TPOLY            329        RES3TPOLY  )
 ( CHIPBLK              351        CHIPBLK    )
 ( SRBLK                352        SRBLK      )
 ( GRBLK                353        GRBLK      )
 ( SRINGBLK             354        SRINGBLK   )
 ( LOGO                 355        LOGO       )
 ( NOSHRINK             356        NOSHRINK   )
 ( NODRC                357        NODRC      )
 ( OPCBLKALL            358        OPCBLKALL  )
 ( DMYBLK               359        DMYBLK     )
 ( NOEBBLK              360        NOEBBLK    )
 ( METBLK               361        METBLK     )
 ( DEUPAD               381        DEUPAD     )
 ( VDD                  382        VDD        )
 ( VSS                  383        VSS        )
 ( NPR                  384        NPR        )
 ( HRPBLK               385        HRPBLK     )
 ( TTXT                 386        TTXT       )
 ( NW1CAP               387        NW1CAP     )
 ( DNW6t                388        DNW6t      )
 ) ;techLayers

 techLayerPurposePriorities(
 ; ( LAYERNAME          PURPOSENAME )
 ; ( =========          =========== )
 ( ZERO                 drawing )
 ( ACT                  drawing )
 ( ACT                  dm )
 ( ACT                  dmblk )
 ( ACT                  res )
 ( ACT                  opcblk )
 ( DNW                  drawing )
 ( NW1                  drawing )
 ( NW1                  res )
 ( NVT1                 drawing )
 ( PVT1                 drawing )
 ( NVT3                 drawing )
 ( PVT3                 drawing )
 ( DGOX                 drawing )
 ( TGOX                 drawing )
 ( POLY                 drawing )
 ( POLY                 dm )
 ( POLY                 dmblk )
 ( POLY                 res )
 ( POLY                 opcblk )
 ( POLY                 text )
 ( POLY                 bar )
 ( NPD                  drawing )
 ( NP                   drawing )
 ( PP                   drawing )
 ( HRP                  drawing )
 ( ESD                  drawing )
 ( SAB                  drawing )
 ( CT                   drawing )
 ( CT                   opcblk )
 ( CT                   bar )
 ( MET1                 drawing )
 ( MET1                 dm )
 ( MET1                 dmblk )
 ( MET1                 res )
 ( MET1                 opcblk )
 ( MET1                 text )
 ( MET1                 slot )
 ( MET1                 slotblk )
 ( MET1                 mom )
 ( MET2                 drawing )
 ( MET2                 dm )
 ( MET2                 dmblk )
 ( MET2                 res )
 ( MET2                 opcblk )
 ( MET2                 text )
 ( MET2                 slot )
 ( MET2                 slotblk )
 ( MET2                 mom )
 ( MET3                 drawing )
 ( MET3                 dm )
 ( MET3                 dmblk )
 ( MET3                 res )
 ( MET3                 opcblk )
 ( MET3                 text )
 ( MET3                 slot )
 ( MET3                 slotblk )
 ( MET3                 mom )
 ( MET4                 drawing )
 ( MET4                 dm )
 ( MET4                 dmblk )
 ( MET4                 res )
 ( MET4                 opcblk )
 ( MET4                 text )
 ( MET4                 slot )
 ( MET4                 slotblk )
 ( MET4                 mom )
 ( MET5                 drawing )
 ( MET5                 dm )
 ( MET5                 dmblk )
 ( MET5                 res )
 ( MET5                 opcblk )
 ( MET5                 text )
 ( MET5                 slot )
 ( MET5                 slotblk )
 ( MET5                 mom )
 ( MET6                 drawing )
 ( MET6                 dm )
 ( MET6                 dmblk )
 ( MET6                 res )
 ( MET6                 opcblk )
 ( MET6                 text )
 ( MET6                 slot )
 ( MET6                 slotblk )
 ( MET6                 mom )
 ( MET7                 drawing )
 ( MET7                 dm )
 ( MET7                 dmblk )
 ( MET7                 res )
 ( MET7                 opcblk )
 ( MET7                 text )
 ( MET7                 slot )
 ( MET7                 slotblk )
 ( MET7                 mom )
 ( MET8                 drawing )
 ( MET8                 dm )
 ( MET8                 dmblk )
 ( MET8                 res )
 ( MET8                 opcblk )
 ( MET8                 text )
 ( MET8                 slot )
 ( MET8                 slotblk )
 ( MET8                 mom )
 ( VIA1                 drawing )
 ( VIA1                 bar )
 ( VIA2                 drawing )
 ( VIA2                 bar )
 ( VIA3                 drawing )
 ( VIA3                 bar )
 ( VIA4                 drawing )
 ( VIA4                 bar )
 ( VIA5                 drawing )
 ( VIA5                 bar )
 ( VIA6                 drawing )
 ( VIA6                 bar )
 ( VIA7                 drawing )
 ( VIA7                 bar )
 ( T2M1                 drawing )
 ( T2M1                 dm )
 ( T2M1                 dmblk )
 ( T2M1                 res )
 ( T2M1                 opcblk )
 ( T2M1                 text )
 ( T2M1                 slot )
 ( T2M1                 slotblk )
 ( T2M2                 drawing )
 ( T2M2                 dm )
 ( T2M2                 dmblk )
 ( T2M2                 res )
 ( T2M2                 opcblk )
 ( T2M2                 text )
 ( T2M2                 slot )
 ( T2M2                 slotblk )
 ( T4M1                 drawing )
 ( T4M1                 dm )
 ( T4M1                 dmblk )
 ( T4M1                 res )
 ( T4M1                 opcblk )
 ( T4M1                 text )
 ( T4M1                 slot )
 ( T4M1                 slotblk )
 ( T4M2                 drawing )
 ( T4M2                 dm )
 ( T4M2                 dmblk )
 ( T4M2                 res )
 ( T4M2                 opcblk )
 ( T4M2                 text )
 ( T4M2                 slot )
 ( T4M2                 slotblk )
 ( T8M1                 drawing )
 ( T8M1                 dm )
 ( T8M1                 dmblk )
 ( T8M1                 res )
 ( T8M1                 opcblk )
 ( T8M1                 text )
 ( T8M1                 slot )
 ( T8M1                 slotblk )
 ( T8M2                 drawing )
 ( T8M2                 dm )
 ( T8M2                 dmblk )
 ( T8M2                 res )
 ( T8M2                 opcblk )
 ( T8M2                 text )
 ( T8M2                 slot )
 ( T8M2                 slotblk )
 ( T2V1                 drawing )
 ( T2V1                 bar )
 ( T2V2                 drawing )
 ( T2V2                 bar )
 ( T4V1                 drawing )
 ( T4V1                 bar )
 ( T4V2                 drawing )
 ( T4V2                 bar )
 ( T8V1                 drawing )
 ( T8V1                 bar )
 ( T8V2                 drawing )
 ( T8V2                 bar )
 ( RV                   drawing )
 ( CB                   drawing )
 ( CB                   text )
 ( ALPAD                drawing )
 ( ALPAD                res )
 ( ALPAD                text )
 ( ALPAD                slot )
 ( ALPAD                slotblk )
 ( RDL                  drawing )
 ( RDL                  text )
 ( COVER                drawing )
 ( BMIM                 drawing )
 ( TMIM                 drawing )
 ( IO                   mark )
 ( CORE                 mark )
 ( ULLD                 mark )
 ( UD                   mark )
 ( OD                   mark )
 ( SRAMALL              mark )
 ( SRAMPG               mark )
 ( SRAM6THD             mark )
 ( SRAM6THS             mark )
 ( SRAM8THD             mark )
 ( SRAM8THS             mark )
 ( DIODE                mark )
 ( VARA                 mark )
 ( VARAM                mark )
 ( VARAJ                mark )
 ( BJT                  mark )
 ( LDMOS                mark )
 ( ESDIOT               mark )
 ( ESDIOE               mark )
 ( RFALL                mark )
 ( RFD                  mark )
 ( RFTER                mark )
 ( PSUB                 mark )
 ( CAP                  mark )
 ( MOMCAP               mark )
 ( MOMTER               mark )
 ( FUTR                 mark )
 ( FUSEALL              mark )
 ( EFUSEALL             mark )
 ( POEFUSEBLK           mark )
 ( INDDMY               mark )
 ( INDALL               mark )
 ( INDVIA               mark )
 ( NOLVS                mark )
 ( MOSMF                mark )
 ( SUBCKTLVS            mark )
 ( RESCKTLVS            mark )
 ( MOSCKTLVS            mark )
 ( LATCHUP              mark )
 ( RFSDLVS              mark )
 ( RF5TERLVS            mark )
 ( RF6TERLVS            mark )
 ( VARAJMRK             mark )
 ( LDMOSSTI             mark )
 ( FUSEDRC              mark )
 ( MOMLVS1              mark )
 ( MOMLVS2              mark )
 ( MOMLVS3              mark )
 ( MOMLVS4              mark )
 ( MOMLVS5              mark )
 ( MOMLVS6              mark )
 ( RES3TPOLY            mark )
 ( CHIPBLK              mark )
 ( SRBLK                mark )
 ( GRBLK                mark )
 ( SRINGBLK             mark )
 ( LOGO                 mark )
 ( NOSHRINK             mark )
 ( NODRC                mark )
 ( OPCBLKALL            mark )
 ( DMYBLK               mark )
 ( NOEBBLK              mark )
 ( METBLK               mark )
 ( DEUPAD               mark )
 ( VDD                  mark )
 ( VSS                  mark )
 ( NPR                  mark )
 ( HRPBLK               mark )
 ( TTXT                 mark )
 ( NW1CAP               mark )
 ( DNW6t                mark )
 ) ;techLayerPurposePriorities

 techDisplays(
 ; ( LAYERNAME          PURPOSENAME          PACKET[FILLCOLOR LINECOLOR LINE STIPPLE]          VIS SEL CON2CHGlY DRGENBL VALID )
 ; ( =========          ===========          ========================================          === === ========= ======= ===== )
 ( ZERO                 drawing             zero                 t t t t t )
 ( ACT                  drawing             act                  t t t t t )
 ( ACT                  dm                  actd                 t t t t t )
 ( ACT                  dmblk               actdb                t t t t t )
 ( ACT                  res                 actr                 t t t t t )
 ( ACT                  opcblk              acto                 t t t t t )
 ( DNW                  drawing             dnw                  t t t t t )
 ( NW1                  drawing             nw1                  t t t t t )
 ( NW1                  res                 nw1r                 t t t t t )
 ( NVT1                 drawing             nvt1                 t t t t t )
 ( PVT1                 drawing             pvt1                 t t t t t )
 ( NVT3                 drawing             nvt3                 t t t t t )
 ( PVT3                 drawing             pvt3                 t t t t t )
 ( DGOX                 drawing             dgox                 t t t t t )
 ( TGOX                 drawing             tgox                 t t t t t )
 ( POLY                 drawing             poly                 t t t t t )
 ( POLY                 dm                  polyd                t t t t t )
 ( POLY                 dmblk               polydb               t t t t t )
 ( POLY                 res                 polyr                t t t t t )
 ( POLY                 opcblk              polyo                t t t t t )
 ( POLY                 text                polyt                t t t t t )
 ( POLY                 bar                 polyb                t t t t t )
 ( NPD                  drawing             npd                  t t t t t )
 ( NP                   drawing             np                   t t t t t )
 ( PP                   drawing             pp                   t t t t t )
 ( HRP                  drawing             hrp                  t t t t t )
 ( ESD                  drawing             esd                  t t t t t )
 ( SAB                  drawing             sab                  t t t t t )
 ( CT                   drawing             ct                   t t t t t )
 ( CT                   opcblk              cto                  t t t t t )
 ( CT                   bar                 ctb                  t t t t t )
 ( MET1                 drawing             m1                   t t t t t )
 ( MET1                 dm                  m1d                  t t t t t )
 ( MET1                 dmblk               m1db                 t t t t t )
 ( MET1                 res                 m1r                  t t t t t )
 ( MET1                 opcblk              m1o                  t t t t t )
 ( MET1                 text                m1t                  t t t t t )
 ( MET1                 slot                m1s                  t t t t t )
 ( MET1                 slotblk             m1sb                 t t t t t )
 ( MET1                 mom                 m1m                  t t t t t )
 ( MET2                 drawing             m2                   t t t t t )
 ( MET2                 dm                  m2d                  t t t t t )
 ( MET2                 dmblk               m2db                 t t t t t )
 ( MET2                 res                 m2r                  t t t t t )
 ( MET2                 opcblk              m2o                  t t t t t )
 ( MET2                 text                m2t                  t t t t t )
 ( MET2                 slot                m2s                  t t t t t )
 ( MET2                 slotblk             m2sb                 t t t t t )
 ( MET2                 mom                 m2m                  t t t t t )
 ( MET3                 drawing             m3                   t t t t t )
 ( MET3                 dm                  m3d                  t t t t t )
 ( MET3                 dmblk               m3db                 t t t t t )
 ( MET3                 res                 m3r                  t t t t t )
 ( MET3                 opcblk              m3o                  t t t t t )
 ( MET3                 text                m3t                  t t t t t )
 ( MET3                 slot                m3s                  t t t t t )
 ( MET3                 slotblk             m3sb                 t t t t t )
 ( MET3                 mom                 m3m                  t t t t t )
 ( MET4                 drawing             m4                   t t t t t )
 ( MET4                 dm                  m4d                  t t t t t )
 ( MET4                 dmblk               m4db                 t t t t t )
 ( MET4                 res                 m4r                  t t t t t )
 ( MET4                 opcblk              m4o                  t t t t t )
 ( MET4                 text                m4t                  t t t t t )
 ( MET4                 slot                m4s                  t t t t t )
 ( MET4                 slotblk             m4sb                 t t t t t )
 ( MET4                 mom                 m4m                  t t t t t )
 ( MET5                 drawing             m5                   t t t t t )
 ( MET5                 dm                  m5d                  t t t t t )
 ( MET5                 dmblk               m5db                 t t t t t )
 ( MET5                 res                 m5r                  t t t t t )
 ( MET5                 opcblk              m5o                  t t t t t )
 ( MET5                 text                m5t                  t t t t t )
 ( MET5                 slot                m5s                  t t t t t )
 ( MET5                 slotblk             m5sb                 t t t t t )
 ( MET5                 mom                 m5m                  t t t t t )
 ( MET6                 drawing             m6                   t t t t t )
 ( MET6                 dm                  m6d                  t t t t t )
 ( MET6                 dmblk               m6db                 t t t t t )
 ( MET6                 res                 m6r                  t t t t t )
 ( MET6                 opcblk              m6o                  t t t t t )
 ( MET6                 text                m6t                  t t t t t )
 ( MET6                 slot                m6s                  t t t t t )
 ( MET6                 slotblk             m6sb                 t t t t t )
 ( MET6                 mom                 m6m                  t t t t t )
 ( MET7                 drawing             m7                   t t t t t )
 ( MET7                 dm                  m7d                  t t t t t )
 ( MET7                 dmblk               m7db                 t t t t t )
 ( MET7                 res                 m7r                  t t t t t )
 ( MET7                 opcblk              m7o                  t t t t t )
 ( MET7                 text                m7t                  t t t t t )
 ( MET7                 slot                m7s                  t t t t t )
 ( MET7                 slotblk             m7sb                 t t t t t )
 ( MET7                 mom                 m7m                  t t t t t )
 ( MET8                 drawing             m8                   t t t t t )
 ( MET8                 dm                  m8d                  t t t t t )
 ( MET8                 dmblk               m8db                 t t t t t )
 ( MET8                 res                 m8r                  t t t t t )
 ( MET8                 opcblk              m8o                  t t t t t )
 ( MET8                 text                m8t                  t t t t t )
 ( MET8                 slot                m8s                  t t t t t )
 ( MET8                 slotblk             m8sb                 t t t t t )
 ( MET8                 mom                 m8m                  t t t t t )
 ( VIA1                 drawing             v1                   t t t t t )
 ( VIA1                 bar                 v1b                  t t t t t )
 ( VIA2                 drawing             v2                   t t t t t )
 ( VIA2                 bar                 v2b                  t t t t t )
 ( VIA3                 drawing             v3                   t t t t t )
 ( VIA3                 bar                 v3b                  t t t t t )
 ( VIA4                 drawing             v4                   t t t t t )
 ( VIA4                 bar                 v4b                  t t t t t )
 ( VIA5                 drawing             v5                   t t t t t )
 ( VIA5                 bar                 v5b                  t t t t t )
 ( VIA6                 drawing             v6                   t t t t t )
 ( VIA6                 bar                 v6b                  t t t t t )
 ( VIA7                 drawing             v7                   t t t t t )
 ( VIA7                 bar                 v7b                  t t t t t )
 ( T2M1                 drawing             t2m1                 t t t t t )
 ( T2M1                 dm                  t2m1d                t t t t t )
 ( T2M1                 dmblk               t2m1db               t t t t t )
 ( T2M1                 res                 t2m1r                t t t t t )
 ( T2M1                 opcblk              t2m1o                t t t t t )
 ( T2M1                 text                t2m1t                t t t t t )
 ( T2M1                 slot                t2m1s                t t t t t )
 ( T2M1                 slotblk             t2m1sb               t t t t t )
 ( T2M2                 drawing             t2m2                 t t t t t )
 ( T2M2                 dm                  t2m2d                t t t t t )
 ( T2M2                 dmblk               t2m2db               t t t t t )
 ( T2M2                 res                 t2m2r                t t t t t )
 ( T2M2                 opcblk              t2m2o                t t t t t )
 ( T2M2                 text                t2m2t                t t t t t )
 ( T2M2                 slot                t2m2s                t t t t t )
 ( T2M2                 slotblk             t2m2sb               t t t t t )
 ( T4M1                 drawing             t4m1                 t t t t t )
 ( T4M1                 dm                  t4m1d                t t t t t )
 ( T4M1                 dmblk               t4m1db               t t t t t )
 ( T4M1                 res                 t4m1r                t t t t t )
 ( T4M1                 opcblk              t4m1o                t t t t t )
 ( T4M1                 text                t4m1t                t t t t t )
 ( T4M1                 slot                t4m1s                t t t t t )
 ( T4M1                 slotblk             t4m1sb               t t t t t )
 ( T4M2                 drawing             t4m2                 t t t t t )
 ( T4M2                 dm                  t4m2d                t t t t t )
 ( T4M2                 dmblk               t4m2db               t t t t t )
 ( T4M2                 res                 t4m2r                t t t t t )
 ( T4M2                 opcblk              t4m2o                t t t t t )
 ( T4M2                 text                t4m2t                t t t t t )
 ( T4M2                 slot                t4m2s                t t t t t )
 ( T4M2                 slotblk             t4m2sb               t t t t t )
 ( T8M1                 drawing             t8m1                 t t t t t )
 ( T8M1                 dm                  t8m1d                t t t t t )
 ( T8M1                 dmblk               t8m1db               t t t t t )
 ( T8M1                 res                 t8m1r                t t t t t )
 ( T8M1                 opcblk              t8m1o                t t t t t )
 ( T8M1                 text                t8m1t                t t t t t )
 ( T8M1                 slot                t8m1s                t t t t t )
 ( T8M1                 slotblk             t8m1sb               t t t t t )
 ( T8M2                 drawing             t8m2                 t t t t t )
 ( T8M2                 dm                  t8m2d                t t t t t )
 ( T8M2                 dmblk               t8m2db               t t t t t )
 ( T8M2                 res                 t8m2r                t t t t t )
 ( T8M2                 opcblk              t8m2o                t t t t t )
 ( T8M2                 text                t8m2t                t t t t t )
 ( T8M2                 slot                t8m2s                t t t t t )
 ( T8M2                 slotblk             t8m2sb               t t t t t )
 ( T2V1                 drawing             t2v1                 t t t t t )
 ( T2V1                 bar                 t2v1b                t t t t t )
 ( T2V2                 drawing             t2v2                 t t t t t )
 ( T2V2                 bar                 t2v2b                t t t t t )
 ( T4V1                 drawing             t4v1                 t t t t t )
 ( T4V1                 bar                 t4v1b                t t t t t )
 ( T4V2                 drawing             t4v2                 t t t t t )
 ( T4V2                 bar                 t4v2b                t t t t t )
 ( T8V1                 drawing             t8v1                 t t t t t )
 ( T8V1                 bar                 t8v1b                t t t t t )
 ( T8V2                 drawing             t8v2                 t t t t t )
 ( T8V2                 bar                 t8v2b                t t t t t )
 ( RV                   drawing             rv                   t t t t t )
 ( CB                   drawing             cb                   t t t t t )
 ( CB                   text                cbt                  t t t t t )
 ( ALPAD                drawing             alpad                t t t t t )
 ( ALPAD                res                 alpadr               t t t t t )
 ( ALPAD                text                alpadt               t t t t t )
 ( ALPAD                slot                alpads               t t t t t )
 ( ALPAD                slotblk             alpadsb              t t t t t )
 ( RDL                  drawing             rdl                  t t t t t )
 ( RDL                  text                rdlt                 t t t t t )
 ( COVER                drawing             cover                t t t t t )
 ( BMIM                 drawing             bmim                 t t t t t )
 ( TMIM                 drawing             tmim                 t t t t t )
 ( IO                   mark                io                   t t t t t )
 ( CORE                 mark                core                 t t t t t )
 ( ULLD                 mark                ulld                 t t t t t )
 ( UD                   mark                ud                   t t t t t )
 ( OD                   mark                od                   t t t t t )
 ( SRAMALL              mark                sramall              t t t t t )
 ( SRAMPG               mark                srampg               t t t t t )
 ( SRAM6THD             mark                sram6d               t t t t t )
 ( SRAM6THS             mark                sram6s               t t t t t )
 ( SRAM8THD             mark                sram8d               t t t t t )
 ( SRAM8THS             mark                sram8s               t t t t t )
 ( DIODE                mark                diode                t t t t t )
 ( VARA                 mark                vara                 t t t t t )
 ( VARAM                mark                varam                t t t t t )
 ( VARAJ                mark                varaj                t t t t t )
 ( BJT                  mark                bjt                  t t t t t )
 ( LDMOS                mark                ldmos                t t t t t )
 ( ESDIOT               mark                esdiot               t t t t t )
 ( ESDIOE               mark                esdioe               t t t t t )
 ( RFALL                mark                rfall                t t t t t )
 ( RFD                  mark                rfd                  t t t t t )
 ( RFTER                mark                rfter                t t t t t )
 ( PSUB                 mark                psub                 t t t t t )
 ( CAP                  mark                cap                  t t t t t )
 ( MOMCAP               mark                momcap               t t t t t )
 ( MOMTER               mark                momter               t t t t t )
 ( FUTR                 mark                futr                 t t t t t )
 ( FUSEALL              mark                fuall                t t t t t )
 ( EFUSEALL             mark                efuall               t t t t t )
 ( POEFUSEBLK           mark                poefublk             t t t t t )
 ( INDDMY               mark                inddm                t t t t t )
 ( INDALL               mark                indall               t t t t t )
 ( INDVIA               mark                indvia               t t t t t )
 ( NOLVS                mark                nolvs                t t t t t )
 ( MOSMF                mark                mosmf                t t t t t )
 ( SUBCKTLVS            mark                sublvs               t t t t t )
 ( RESCKTLVS            mark                rescktlvs            t t t t t )
 ( MOSCKTLVS            mark                moscktlvs            t t t t t )
 ( LATCHUP              mark                latchup              t t t t t )
 ( RFSDLVS              mark                rflvs                t t t t t )
 ( RF5TERLVS            mark                rf5tlvs              t t t t t )
 ( RF6TERLVS            mark                rf6tlvs              t t t t t )
 ( VARAJMRK             mark                varjmrk              t t t t t )
 ( LDMOSSTI             mark                ldmosti              t t t t t )
 ( FUSEDRC              mark                fusedrc              t t t t t )
 ( MOMLVS1              mark                momlvs1              t t t t t )
 ( MOMLVS2              mark                momlvs2              t t t t t )
 ( MOMLVS3              mark                momlvs3              t t t t t )
 ( MOMLVS4              mark                momlvs4              t t t t t )
 ( MOMLVS5              mark                momlvs5              t t t t t )
 ( MOMLVS6              mark                momlvs6              t t t t t )
 ( RES3TPOLY            mark                res3tpoly            t t t t t )
 ( CHIPBLK              mark                chipblk              t t t t t )
 ( SRBLK                mark                srblk                t t t t t )
 ( GRBLK                mark                grblk                t t t t t )
 ( SRINGBLK             mark                sringblk             t t t t t )
 ( LOGO                 mark                logo                 t t t t t )
 ( NOSHRINK             mark                noshrink             t t t t t )
 ( NODRC                mark                nodrc                t t t t t )
 ( OPCBLKALL            mark                opcblk               t t t t t )
 ( DMYBLK               mark                dmyblk               t t t t t )
 ( NOEBBLK              mark                noebblk              t t t t t )
 ( METBLK               mark                metblk               t t t t t )
 ( DEUPAD               mark                deupad               t t t t t )
 ( VDD                  mark                vdd                  t t t t t )
 ( VSS                  mark                vss                  t t t t t )
 ( NPR                  mark                npr                  t t t t t )
 ( HRPBLK               mark                hrpblk               t t t t t )
 ( TTXT                 mark                ttxt                 t t t t t )
 ( NW1CAP               mark                nw1c                 t t t t t )
 ( DNW6t                mark                dnw6t                t t t t t )
 ) ;techDisplays

 techDerivedLayers(
 ; ( DERIVEDLAYERNAME          DERIVEDLAYERNUM          COMPOSITION )
 ; ( ================          ===============          =========== )
 ( gate                 10003      ( POLY                 'and       ACT ))
 ( nACT                 10004      ( ACT                  'and       NP ))
 ( pACT                 10005      ( ACT                  'and       PP ))
 ( ntap                 10006      ( nACT                 'and       NW1 ))
 ( ptap                 10007      ( pACT                 'not       NW1 ))
 ( ndiff                10008      ( nACT                 'not       NW1 ))
 ( pdiff                10009      ( pACT                 'and       NW1 ))
 ( ndiffDG              10010      ( nACT                 'and       DGOX ))
 ( ndiffTG              10011      ( nACT                 'and       TGOX ))
 ( ndiffInDnw           10012      ( nACT                 'and       DNW ))
 ( SNSP                 10371      ( NP                   'or        PP ))
 ( SABAA                10401      ( SAB                  'and       ACT ))
 ) ;techDerivedLayers


) ;layerDefinitions

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; LAYER RULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
layerRules(
 functions(
 ; ( LAYER              FUNCTION          [MASKNUMBER] )
 ; ( =====              ========          ============ )
 ( RDL                  "metal"              123        )
 ( RV                   "cut"                120        )
 ( T4V2                 "cut"                112        )
 ( T4M2                 "metal"              102        )
 ( VIA5                 "cut"                95         )
 ( VIA4                 "cut"                94         )
 ( VIA3                 "cut"                93         )
 ( VIA2                 "cut"                92         )
 ( VIA1                 "cut"                91         )
 ( MET6                 "metal"              86         )
 ( MET5                 "metal"              85         )
 ( MET4                 "metal"              84         )
 ( MET3                 "metal"              83         )
 ( MET2                 "metal"              82         )
 ( MET1                 "metal"              81         )
 ( CT                   "cut"                72         )
 ( SAB                  "recognition"        71         )
 ( PP                   "pplus"              53         )
 ( NP                   "nplus"              52         )
 ( POLY                 "poly"               41         )
 ( NW1                  "nwell"              9          )
 ( DNW                  "deepNwell"          7          )
 ( ACT                  "diff"               2          )
 ) ;functions

 routingDirections(
 ; ( LAYER              DIRECTION )
 ; ( =====              ========= )
 ( POLY                 "none" )
 ( MET1                 "horizontal" )
 ( MET2                 "vertical" )
 ( MET3                 "horizontal" )
 ( MET4                 "vertical" )
 ( MET5                 "horizontal" )
 ( MET6                 "vertical" )
 ( T4M2                 "horizontal" )
 ( RDL                  "vertical" )
 ) ;routingDirections

 stampLabelLayers(
 ; ( TEXTLAYER          LAYERS )
 ; ( =========          ====== )
 ( MET1                 ( MET1 text )        ( MET1 drawing ) )
 ( MET2                 ( MET2 text )        ( MET2 drawing ) )
 ( MET3                 ( MET3 text )        ( MET3 drawing ) )
 ( MET4                 ( MET4 text )        ( MET4 drawing ) )
 ( MET5                 ( MET5 text )        ( MET5 drawing ) )
 ( MET6                 ( MET6 text )        ( MET6 drawing ) )
 ( T4M2                 ( T4M2 text )        ( T4M2 drawing ) )
 ( RDL                  ( ALPAD text )       ( RDL drawing ) )
 ) ;stampLabelLayers


) ;layerRules

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; VIA DEFS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
viaDefs(
 standardViaDefs(
 ; ( VIADEFNAME LAYER1 LAYER2 ( CUTLAYER CUTWIDTH CUTHEIGHT [RESISITANCEPERCUT] )
 ;     ( CUTROWS CUTCOLS ( CUTSPACE ))
 ;     ( LAYER1ENC ) ( LAYER2ENC ) ( LAYER1OFFSET ) ( LAYER2OFFSET ) ( ORIGOFFSET )
 ;     [ IMPLANT1 ( IMPLANT1ENC ) [ IMPLANT2 ( IMPLANT2ENC ) [WELL/SUBSTRATE]]] )
 ; ( ========================================================================== )
 ( MET1_SUB             ACT                  MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.03 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
     PP  ( 0.02 0.02 )    )

 ( MET1_NW1             ACT                  MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.03 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
     NP  ( 0.02 0.02 )    NW1  ( 0.15 0.15 )    )

 ( MET1_PP              ACT                  MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.03 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
     PP  ( 0.02 0.02 )    )

 ( MET1_NP              ACT                  MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.03 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
     NP  ( 0.02 0.02 )    )

 ( MET1_ACT             ACT                  MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.03 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET1_POLY            POLY                 MET1                 ( CT  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.04 0.04 )   ( 0.025 0 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET2_MET1            MET1                 MET2                 ( VIA1  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0 )   ( 0.02 0.005 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET3_MET2            MET2                 MET3                 ( VIA2  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.005 )   ( 0.02 0.005 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET4_MET3            MET3                 MET4                 ( VIA3  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.005 )   ( 0.02 0.005 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET5_MET4            MET4                 MET5                 ( VIA4  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.005 )   ( 0.02 0.005 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( MET6_MET5            MET5                 MET6                 ( VIA5  0.09   0.09  0 )
     ( 1 1  ( 0.11 0.11 )  ) 
     ( 0.03 0.005 )   ( 0.02 0.005 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( T4M2_MET6            MET6                 T4M2                 ( T4V2  0.36   0.36  0 )
     ( 1 1  ( 0.34 0.34 )  ) 
     ( 0.01 0.05 )   ( 0.02 0.02 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ( RDL_T4M2             T4M2                 RDL                  ( RV  3   3  0 )
     ( 1 1  ( 3 3 )  ) 
     ( 1.5 1.5 )   ( 1.5 1.5 )   ( 0 0 )   ( 0 0 )   ( 0 0 ) 
      )

 ) ;standardViaDefs


) ;viaDefs

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; CONSTRAINT GROUPS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
constraintGroups(
 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "hesDefaultExtractorSetup"    nil          

 interconnect(
 ( validLayers           ( NW1 ACT POLY CT MET1 VIA1 MET2 VIA2 MET3 VIA3 MET4 VIA4 MET5 VIA5 MET6 T4V2 T4M2 RV RDL ) )
 ( validVias             ( MET1_POLY MET1_NW1 MET1_SUB MET1_NP MET1_PP MET1_ACT MET2_MET1 MET3_MET2 MET4_MET3 MET5_MET4 MET6_MET5 T4M2_MET6 RDL_T4M2 ) )
 ); interconnect

); hesDefaultExtractorSetup

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "hesDefaultTaper"    nil     "taper"     

 interconnect(
 ( validLayers           ( POLY MET1 ) )
 ( validVias             ( MET1_POLY ) )
 ); interconnect

 spacings(
 ( taperHalo              0 )
 ); spacings

); hesDefaultTaper

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "hesDefaultSetup"    nil          

 interconnect(
 ( validLayers           ( NW1 ACT POLY MET1 MET2 MET3 MET4 MET5 MET6 T4M2 RDL ) )
 ( validVias             ( MET1_POLY MET1_NW1 MET1_SUB MET1_NP MET1_PP MET1_ACT MET2_MET1 MET3_MET2 MET4_MET3 MET5_MET4 MET6_MET5 T4M2_MET6 RDL_T4M2 ) )
 ); interconnect

); hesDefaultSetup

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "VLMDefaultSetup"    nil          

 interconnect(
 ( validLayers           ( NW1 ACT POLY CT MET1 VIA1 MET2 VIA2 MET3 VIA3 MET4 VIA4 MET5 VIA5 MET6 T4V2 T4M2 RV RDL ) )
 ( validVias             ( MET1_POLY MET1_NW1 MET1_SUB MET1_NP MET1_PP MET1_ACT MET2_MET1 MET3_MET2 MET4_MET3 MET5_MET4 MET6_MET5 T4M2_MET6 RDL_T4M2 ) )
 ); interconnect

); VLMDefaultSetup

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "LEFDefaultRouteSpec"    nil          

 interconnect(
 ( validLayers           ( NW1 ACT POLY MET1 MET2 MET3 MET4 MET5 MET6 T4M2 RDL ) )
 ( validVias             ( MET2_MET1 MET3_MET2 MET4_MET3 MET5_MET4 MET6_MET5 T4M2_MET6 RDL_T4M2 ) )
 ); interconnect

 spacings(
 ( minWidth              "CT"                  0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET1"                0.18  )
 ( verticalPitch         "MET1"                0.18  )
 ( horizontalOffset      "MET1"                0  )
 ( verticalOffset        "MET1"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET1"                0.09  )
 ( minWidth              "VIA1"                0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET2"                0.2  )
 ( verticalPitch         "MET2"                0.2  )
 ( horizontalOffset      "MET2"                0  )
 ( verticalOffset        "MET2"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET2"                0.1  )
 ( minWidth              "VIA2"                0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET3"                0.2  )
 ( verticalPitch         "MET3"                0.2  )
 ( horizontalOffset      "MET3"                0  )
 ( verticalOffset        "MET3"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET3"                0.1  )
 ( minWidth              "VIA3"                0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET4"                0.2  )
 ( verticalPitch         "MET4"                0.2  )
 ( horizontalOffset      "MET4"                0  )
 ( verticalOffset        "MET4"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET4"                0.1  )
 ( minWidth              "VIA4"                0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET5"                0.2  )
 ( verticalPitch         "MET5"                0.2  )
 ( horizontalOffset      "MET5"                0  )
 ( verticalOffset        "MET5"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET5"                0.1  )
 ( minWidth              "VIA5"                0.09  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "MET6"                0.2  )
 ( verticalPitch         "MET6"                0.2  )
 ( horizontalOffset      "MET6"                0  )
 ( verticalOffset        "MET6"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "MET6"                0.1  )
 ( minWidth              "T4V2"                0.36  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "T4M2"                0.8  )
 ( verticalPitch         "T4M2"                0.8  )
 ( horizontalOffset      "T4M2"                0  )
 ( verticalOffset        "T4M2"                0  )
 ); routingGrids

 spacings(
 ( minWidth              "T4M2"                0.4  )
 ( minWidth              "RV"                  3  )
 ); spacings

 routingGrids(
 ( horizontalPitch       "RDL"                 5  )
 ( verticalPitch         "RDL"                 5  )
 ( horizontalOffset      "RDL"                 0  )
 ( verticalOffset        "RDL"                 0  )
 ); routingGrids

 spacings(
 ( minWidth              "RDL"                 3  )
 ); spacings

); LEFDefaultRouteSpec

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "foundry"    nil          

 interconnect(
 ( validLayers           ( NW1 ACT POLY CT MET1 VIA1 MET2 VIA2 MET3 VIA3 MET4 VIA4 MET5 VIA5 MET6 T4V2 T4M2 RV RDL ) )
 ( validVias             ( MET1_POLY MET1_NW1 MET1_SUB MET1_NP MET1_PP MET1_ACT MET2_MET1 MET3_MET2 MET4_MET3 MET5_MET4 MET6_MET5 T4M2_MET6 RDL_T4M2 ) )
 ); interconnect

 spacings(
 ( minWidth              "DNW"                 3  )
 ( minSpacing            "DNW"                 3.5  )
 ( minWidth              "ACT"                 0.08  )
 ( minArea               "ACT"                 0.0384  )
 ( minWidth              "NW1"                 0.47  )
 ( minArea               "NW1"                 0.3  )
 ( minWidth              "TGOX"                0.47  )
 ( minSpacing            "TGOX"                0.47  )
 ( minWidth              "DGOX"                0.47  )
 ( minSpacing            "DGOX"                0.47  )
 ( minWidth              "POLY"                0.06  )
 ( minSpacing            "POLY"                0.12  )
 ( minArea               "POLY"                0.04  )
 ( minWidth              "NP"                  0.18  )
 ( minSpacing            "NP"                  0.18  )
 ( minArea               "NP"                  0.12  )
 ( minWidth              "PP"                  0.18  )
 ( minSpacing            "PP"                  0.18  )
 ( minArea               "PP"                  0.12  )
 ( minWidth              "SAB"                 0.42  )
 ( minSpacing            "SAB"                 0.42  )
 ( minArea               "SAB"                 0.8  )
 ( minWidth              "CT"                  0.09  )
 ( maxWidth              "CT"                  0.09  )
 ( minSpacing            "CT"                  0.11  )
 ( minLargeViaArrayWidth  "CT"                  0.7  )
 ( minLargeViaArrayCutSpacing  "CT"                  0.14  'ref "CT-S.1a" )
 ( minWidth              "MET1"                0.09  )
 ( minSpacing            "MET1"                0.09  )
 ( maxWidth              "MET1"                10  )
 ( minArea               "MET1"                0.042  )
 ( minHoleArea           "MET1"                0.18  )
 ( minWidth              "VIA1"                0.09  )
 ( maxWidth              "VIA1"                0.09  )
 ( minSpacing            "VIA1"                0.11  )
 ( minLargeViaArrayWidth  "VIA1"                0.7  )
 ( minLargeViaArrayCutSpacing  "VIA1"                0.13  'ref "VIAn-S.2" )
 ( minWidth              "MET2"                0.1  )
 ( minSpacing            "MET2"                0.1  )
 ( maxWidth              "MET2"                10  )
 ( minArea               "MET2"                0.052  )
 ( minHoleArea           "MET2"                0.18  )
 ( minWidth              "MET3"                0.1  )
 ( minSpacing            "MET3"                0.1  )
 ( maxWidth              "MET3"                10  )
 ( minArea               "MET3"                0.052  )
 ( minHoleArea           "MET3"                0.18  )
 ( minWidth              "MET4"                0.1  )
 ( minSpacing            "MET4"                0.1  )
 ( maxWidth              "MET4"                10  )
 ( minArea               "MET4"                0.052  )
 ( minHoleArea           "MET4"                0.18  )
 ( minWidth              "MET5"                0.1  )
 ( minSpacing            "MET5"                0.1  )
 ( maxWidth              "MET5"                10  )
 ( minArea               "MET5"                0.052  )
 ( minHoleArea           "MET5"                0.18  )
 ( minWidth              "MET6"                0.1  )
 ( minSpacing            "MET6"                0.1  )
 ( maxWidth              "MET6"                10  )
 ( minArea               "MET6"                0.052  )
 ( minHoleArea           "MET6"                0.18  )
 ( minWidth              "VIA2"                0.09  )
 ( maxWidth              "VIA2"                0.09  )
 ( minSpacing            "VIA2"                0.11  )
 ( minLargeViaArrayWidth  "VIA2"                0.7  )
 ( minLargeViaArrayCutSpacing  "VIA2"                0.13  'ref "VIAn-S.2" )
 ( minWidth              "VIA3"                0.09  )
 ( maxWidth              "VIA3"                0.09  )
 ( minSpacing            "VIA3"                0.11  )
 ( minLargeViaArrayWidth  "VIA3"                0.7  )
 ( minLargeViaArrayCutSpacing  "VIA3"                0.13  'ref "VIAn-S.2" )
 ( minWidth              "VIA4"                0.09  )
 ( maxWidth              "VIA4"                0.09  )
 ( minSpacing            "VIA4"                0.11  )
 ( minLargeViaArrayWidth  "VIA4"                0.7  )
 ( minLargeViaArrayCutSpacing  "VIA4"                0.13  'ref "VIAn-S.2" )
 ( minWidth              "VIA5"                0.09  )
 ( maxWidth              "VIA5"                0.09  )
 ( minSpacing            "VIA5"                0.11  )
 ( minLargeViaArrayWidth  "VIA5"                0.7  )
 ( minLargeViaArrayCutSpacing  "VIA5"                0.13  'ref "VIAn-S.2" )
 ( minWidth              "T4V2"                0.36  )
 ( maxWidth              "T4V2"                0.36  )
 ( minSpacing            "T4V2"                0.34  )
 ( minLargeViaArrayWidth  "T4V2"                1.8  )
 ( minLargeViaArrayCutSpacing  "T4V2"                0.5  'ref "T4V2-S.2" )
 ( minWidth              "T4M2"                0.4  )
 ( minSpacing            "T4M2"                0.4  )
 ( minArea               "T4M2"                0.4  )
 ( minHoleArea           "T4M2"                0.6  )
 ( maxWidth              "T4M2"                20  )
 ( minWidth              "RV"                  3  )
 ( minLength             "RV"                  3  )
 ( minSpacing            "RV"                  3  )
 ( minWidth              "RDL"                 3  )
 ( minSpacing            "RDL"                 2  )
 ( minWidth              "COVER"               40  )
 ( minSpacing            "COVER"               5  )
 ); spacings

 orderedSpacings(
 ( minEnclosure          "NW1"                "DNW"                 1  'ref "DNW-En.1" )
 ( minEnclosure          "NW1"                "nACT"                0.15  'ref "ACT-En.1" )
 ( minEnclosure          "NW1"                "pACT"                0.15  'ref "ACT-En.2" )
 ( minOppExtension       "MET1"               "CT"                 ( 0.04 0 )  'ref "CT-En.3b" )
 ( minOppExtension       "MET1"               "VIA1"               ( 0.04 0 )  'ref "VIAn-En.2*" )
 ( minOppExtension       "MET2"               "VIA1"               ( 0.02 0.005 )  'ref "VIAn-En.5*" )
 ( minOppExtension       "MET2"               "VIA2"               ( 0.04 0 )  'ref "VIAn-En.2*" )
 ( minOppExtension       "MET3"               "VIA2"               ( 0.02 0.005 )  'ref "VIAn-En.5*" )
 ( minOppExtension       "MET3"               "VIA3"               ( 0.04 0 )  'ref "VIAn-En.2*" )
 ( minOppExtension       "MET4"               "VIA3"               ( 0.02 0.005 )  'ref "VIAn-En.5*" )
 ( minOppExtension       "MET4"               "VIA4"               ( 0.04 0 )  'ref "VIAn-En.2*" )
 ( minOppExtension       "MET5"               "VIA4"               ( 0.02 0.005 )  'ref "VIAn-En.5*" )
 ( minOppExtension       "MET5"               "VIA5"               ( 0.04 0 )  'ref "VIAn-En.2*" )
 ( minOppExtension       "MET6"               "VIA5"               ( 0.02 0.005 )  'ref "VIAn-En.5*" )
 ( minOppExtension       "MET6"               "T4V2"               ( 0.05 0.01 )  'ref "T4V2-En.2/3" )
 ( minOppExtension       "T4M2"               "T4V2"               ( 0.02 0.02 )  'ref "T4V2-En.5" )
 ( minOppExtension       "T4M2"               "RV"                 ( 1.5 1.5 )  'ref "RV-En.2" )
 ( minOppExtension       "RDL"                "RV"                 ( 1.5 1.5 )  'ref "RV-En.4" )
 ); orderedSpacings

); foundry

 ; ( group    [override]    [definition]    [operator] )
 ; ( =====    ==========    ============    ========== )
   ( "default"    nil          

); default

) ;constraintGroups

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; DEVICES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
devices(
 flexiblePath(
 ; ( NAME [MASTERPATH] [OFFSETSUBPATHS] [ENCSUBPATHS] [SUBRECTS] )
 ;
 ;   MASTERPATH:
 ;   (LAYER [WIDTH] [CHOPPABLE] [ENDTYPE] [BEGINEXT] [ENDEXT] [JUSTIFY] [OFFSET] [ENCLOSEBY]
 ;   [CONNECTIVITY])
 ;
 ;   OFFSETSUBPATHS:
 ;   (LAYER [WIDTH] [CHOPPABLE] [SEPARATION] [JUSTIFICATION] [BEGOFFSET] [ENDOFFSET]
 ;   [CONNECTIVITY])
 ;
 ;   ENCSUBPATHS:
 ;   (LAYER [ENCLOSURE] [CHOPPABLE] [BEGOFFSET] [ENDOFFSET]
 ;   [CONNECTIVITY])
 ;
 ;   SUBRECTS:
 ;   (LAYER [WIDTH] [LENGTH] [CHOPPABLE] [SEPARATION] [JUSTIFICATION] [SPACE] [BEGOFFSET] [ENDOFFSET] [GAP]
 ;   [BEGINSEGOFFSET] [ENDSEGOFFSET] [DIAGONAL] [CONNECTIVITY])
 ;
 ;   CONNECTIVITY:
 ;   ([I/O TYPE] [PIN] [ACCDIR] [DISPPINNAME] [HEIGHT] [LAYER]
 ;    [LAYER] [JUSTIFICATION] [FONT] [TEXTOPTIONS] [ORIENTATION]
 ;    [REFHANDLE] [OFFSET])
 ;
 ; ( --------------------------------------------------------------------- )
 ( "NGR" 
   ( (  ACT drawing  ) 0.15 t truncate 0 0 center 0 0 nil )
   (
    nil
   )
   (
    ( (  NP drawing  ) -0.03 t 0.03 0.03 nil )
    ( (  NW1 drawing  ) -0.16 t 0.16 0.16 nil )
    ( (  MET1 drawing  ) -0.01 t 0.01 0.01 nil )
   )
   (
    ( (  CT drawing  ) 0.09 0.09 t 0 center 0.11 -0.055 -0.055 distribute 0 0 nil nil )
   )
 )
 ( "PGR" 
   ( (  ACT drawing  ) 0.15 t truncate 0 0 center 0 0 nil )
   (
    nil
   )
   (
    ( (  PP drawing  ) -0.03 t 0.03 0.03 nil )
    ( (  MET1 drawing  ) -0.01 t 0.01 0.01 nil )
   )
   (
    ( (  CT drawing  ) 0.09 0.09 t 0 center 0.11 -0.055 -0.055 distribute 0 0 nil nil )
   )
 )
 ) ;flexiblePath


) ;devices

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; METAL RULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
metalRules(

) ;metalRules

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ROUTE RULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
routeRules(

) ;routeRules

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; SITEDEFS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
siteDefs(

) ;siteDefs

